name: 'repo-backup'
on:
  push:
    branches:
      - main

jobs:
  repo-backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: repo-backup-arweave
        uses: Dhaiwat10/repo-backup-arweave@v0.4
        with:
          arweaveWalletKey: ${{ secrets.ARWEAVE_WALLET_KEY }}
